# docker-tools
#   docker-machine ip default
# docker-compose up -d
# docker-compose restart
# docker-compose stop
# docker-compose rm -v
# docker-compose logs
# docker-compose down -v

version: "3"

services:
  nginx:
    build: ./inc/docker/nginx/
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - "${PROJECT_ROOT}:/var/www/html:ro"
    networks:
      - server

  php:
    build: ./inc/docker/php/
    expose:
      - 9000
    depends_on:
      - mysql
    volumes:
      - "${PROJECT_ROOT}:/var/www/html:ro"
    networks:
      - database
      - server

  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    networks:
      - database
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql

  # sass style.scss
  # sass --help
  sass:
    image: larryprice/sass
    volumes:
      - ./inc:/src
    networks:
      - server

volumes:
  data:

networks:
  database:
  server: